name: deephamx
dependencies:
  - python=3.11.0
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - tqdm
  - quantecon
  - pip
  - pip:
    - seaborn
    - pandas
    - jax[cuda12]
    - dm-haiku
    - optax
    - pickle
    